require 'options'
require 'plugins'
require 'keymaps'
require 'colorscheme'
require 'plugins.cmp'
require 'lsp'
require 'plugins.telescope'
require 'plugins.treesitter'
require 'plugins.autopairs'
require 'plugins.comment'

